apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t714vzl7a-python
  janus-idp.io/tekton: t714vzl7a-python
  backstage.io/kubernetes-id: t714vzl7a-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t714vzl7a-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
