apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: t714vzl7a-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: t714vzl7a-python 
  name: t714vzl7a-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: t714vzl7a-python 
